version: '3.8'

services:
  nginx:
    image: amalthomas964/local-nginx:v1.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network

  python-app:
    image: amalthomas964/local-python-app:v1.1
    container_name: python_app
    expose:
      - "8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
